import "./globals.css";
import AppShell from "../components/AppShell";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="h-full overflow-hidden">
      <body className="h-full overflow-hidden flex flex-col">
        <AppShell>{children}</AppShell>
      </body>
    </html>
  );
}
